name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          pip install pyspark
          pip install -r requirements.txt  # If you have additional dependencies

      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "tests/test_delta_processor.py"
