name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java (required for Spark)
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # Or 'zulu', 'adopt'
          java-version: "11" # Common version for Spark 3.x

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have additional dependencies
          java -version # Verify Java setup
          python --version # Verify Python setup
          pip list # List installed packages

      - name: Run Pytest Integration Tests
        run: |
          pytest tests/test_glue_etl.py -v # -v for verbose output
        env:
          PYSPARK_PYTHON: python # Ensure pytest uses the correct python
          PYSPARK_DRIVER_PYTHON: python
